### ISSUE TITLE
Doesn't show ON in disabled status

### ISSUE THREAD

**Issue by tenphi** [frapontillo/angular-bootstrap-switch#67]
In `disabled` mode switcher doesn't react on model changes and shows only OFF status.

**Comment by frapontillo** [comment]
That is the expected behaviour of the original plugin; you can try it on the [examples page](http://www.bootstrap-switch.org/examples.html) by running the following code in the dev tools console (the disabled switch won't be toggled):

```javascript
$('#switch-disabled').bootstrapSwitch('toggleState');
```

If you feel like you should be able to toggle a disabled switch please open an issue on the [original plugin's bug tracker](https://github.com/nostalgiaz/bootstrap-switch/issues).
Thanks.

**Comment by tenphi** [comment]
Thanks for your answer. I should have tested that with the original plugin.
